// Jenkinsfile amélioré
pipeline {
    agent any
    stages {
        stage('Pulling Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/jcndanou/alx-backend-python.git',
                    credentialsId: 'github-credentials' // Si authentication requise
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Testing') {
            steps {
                sh '''
                    cd messaging_app
                    mkdir -p test-reports
                    pytest --junitxml=test-reports/report.xml
                '''
            }
            post {
                always {
                    junit 'messaging_app/test-reports/report.xml'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'docker build -t my-app-image:latest .'
                        sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                        sh 'docker push my-app-image:latest'
                    }
                }
            }
        }
    }
}