// Jenkinsfile
pipeline {
    agent any
    stages {
        stage('Pulling Code') {
            steps {
                git 'https://github.com/jcndanou/alx-backend-python.git'
            }
        }
        stage('Testing') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest --junitxml=test-reports/report.xml'
            }
        }
        stage('Publishing Test Report') {
            steps {
                sh 'pytest --junitxml=test-reports/report.xml'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // withCredentials permet d'utiliser les identifiants stockés dans Jenkins
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'docker build -t my-app-image:latest .'
                        sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                        sh 'docker push my-app-image:latest'
                    }
                }
            }
        }
    }
}