#!/bin/bash
# Start the Kubernetes cluster
minikube start --driver=virtualbox
# Verify the cluster is running
kubectl cluster-info
# Retrieve the available pods (should be just system pods initially)
kubectl get pods --all-namespaces
